### PR TITLE
Feature/framework target

### PR DESCRIPTION
**Pull request by damtsnkff**
@JakeLin @gkye first time creating a framework, so not sure if this is the way to go, but got this working. (using other cocoapod framework)
I'm pushing it to the develop branch so this could (should) be improved before a release in the master branch.
Let me know what you think (and if it's the right way to do)
_[Right branch this time.]_

### CODE REVIEW

**Comment by gkye** [comment]
Could you also add the files and changes from the most recent merge? (Pull from master)

**Comment by damtsnkff** [comment]
@gkye sure. I'll also add the file from the last commit too.

**Comment by damtsnkff** [comment]
@gkye should be good I guess. Can you check I did not make mistake with the git thing ?
I did `git fetch origin` and `git merge origin/master`, discard the change for the files with conflicts, and commit again.

**Comment by gkye** [comment]
Hmmm for some strange reason there are no targets available in your branch (when workspace is opened) and `.xcodeproj` cannot be opened

**Comment by JakeLin** [comment]
@damtsnkff Please give me some time, I am working on this branch now. And BTW: we make our process even simpler, we don't use "develop" branch. All feature branches go to master directly.

**Comment by JakeLin** [comment]
See #16

**Pull request closed without merging**
