### PR TITLE
Description of How to add an new Element

### PR DESCRIPTION
**Pull request by damtsnkff**
I added some description of how to add new components/elements to the current example app.
Overall, do you think the example app approach is good ? 
I tried to think about something that would give us some modularity.

### CODE REVIEW

**Comment by JakeLin** [comment]
@damtsnkff thanks for your PR. I saw your preview commit too https://github.com/JakeLin/IBAnimatable-Material/commit/dd87168f4e98143ccc7cdd408c138dda4e237e05  Very nice, 👍

In main project `IBAnimatable`, there are two targets. `IBAnimatable` target is a framework tareget. and `IBAnimatableApp` is an app target, which is a demo app.

I think having an example app is good for the project sepically for developing the new features. We can valify the feature by testing the example app.

Also we don't distribute the example app when we create the framework (using CocoaPods, Carthage or Swift Package Manager) for the users. For `IBAnimatable-Material` project, we will creat a framework target and move all `Animatable<MaterialElements>` classes into this target and create a Pod for it. Also create an app target to contain all demo features. `MainTableView` and all storyboards will be in the app target only. App target will use `IBAnimatable-Material` target as a framework. Same as what we are doing in `IBAnimatable.

Later on, the user can use CocoaPods, Carthage or Swift Package Manager to use `IBAnimatable-Material`. `IBAnimatable-Material` pod will depend on `IBAnimatable` and `Material` pods.

Did I answer your question? Please let me know if you have any questions.

**Comment by damtsnkff** [comment]
Using the same architecture as IBAnimatable makes sense, avoid the confusion, and will be easier to understand. Can I do the modification and then commit on the same PR or should I modify and create another PR ?

**Comment by damtsnkff** [comment]
To sum up the modifications to make to this PR : 
- Create a Framework target with `Animatable<MaterialElements>` classes
- Create an App target, that use the new `IBAnimatable-Material` Framework
- Organize the workspace folders in consequence 

Is this all for this PR?

**Comment by JakeLin** [comment]
Related to #3

**Comment by JakeLin** [comment]
Hi Damien, 

it's up to you to merge current one and create another PR for the frameworks. Or you close it and create a new PR only. We don't have restricted rule. Please let me know if you have any questions.

Jake

**Comment by damtsnkff** [comment]
@JakeLin If I merge this one, isn't that going to have conflict with #4 ?
Next PR will be the Framework structure #3  (then another one for the dependency managers #6 ).

**Comment by JakeLin** [comment]
I won't be a conflict because we can rebase the next one. If there is a conflict, we can do it together to resolve it. Git is very good for resolving conflicts.

**Pull request closed without merging**
