### PR TITLE
Add framework and app targets

### PR DESCRIPTION
**Pull request by JakeLin**
@damtsnkff has done a great work on creating framework and app targets.  On top of that, I have reorganized the project structure like this.

screen shot 2016-07-21 at 12 05 45 am

That's not the best practice. Just a starting point for our project, free feel to change it.

It took me hours to fix all merge conflicts since we all changed the Xcode project file. Can you guys review it and merge it into master? I don't want to rebase and merge again for this PR. @damtsnkff  @gkye

### CODE REVIEW

**Comment by JakeLin** [comment]
@damtsnkff Can I delete develop branch since we are not using it?

**Comment by damtsnkff** [comment]
@JakeLin Waw, nice work 👍 ! 
To me, this is working, and ok to merge. Here is some details to note.

**Note:**
- In order to make this work I had to build the Framework Target first, and then run the App target, because I had an `library not loaded` error when opening the storyboard.
- The `AnimatableMaterialCardView` and the `AnimatableImageCardView` constraints that break.

@gkye Did you have the same issues ?

**Comment by JakeLin** [comment]
@damtsnkff I don't have the build issue, even I delete the derived data and rebuild. Don't know whether is environment issue or code issue? If it's code issue, we need to fix it?

@gkye does Material support AutoLayout? Do we need to set the translate mask to disable it?

**Comment by gkye** [comment]
Everything looks good no build issues or broken constraints.
@damtsnkff  what device are you testing on? 

@JakeLin Material does support AutoLayout (it also includes its own AutoLayout API)

**Comment by JakeLin** [comment]
Thanks guys. I merge it first. Will fix the small issues if found.

Jake

**Comment by damtsnkff** [comment]
Cool 👍! Also, you can delete the `develop` branch, I understood the
working process.

**Pull request merged**
